name: Xcode

on: [push]

jobs:
  build:
  
    name: Build and Test
    runs-on: macOS-10.15

    steps:
    
    - uses: actions/checkout@v1

    - name: Build
      env:
        scheme: ${{ matrix.scheme }}
        platform: ${{ matrix.platform }}
        device: ${{ matrix.device }}
      run: |
        swift build
        
    - name: Test
      run: |
        swift test
