name: Xcode

on: [push]

jobs:
  build:
  
    name: Build and Test ${{ matrix.scheme }} for ${{ matrix.device }}
    runs-on: macOS-latest
    
    strategy:
      max-parallel: 6
      matrix:
        # List all schemes to build
        scheme: [default]
        # Specify the platform & devices
        platform: [iOS Simulator]
        device: [iPhone Xs, iPhone Xs Max]
    
    steps:
    
    - uses: actions/checkout@v1
    
      # Runs if matrix.scheme is set to default
      # Finds the first listed scheme
    - name: Set Default Scheme
      if: matrix.scheme == 'default'
      run: |
        scheme_list=$(xcodebuild -list -json | tr -d "\n")
        default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['workspace']['schemes'][0]")
        echo $default | cat >default
        echo Using default scheme: $default
    
    - name: Build
      env:
        scheme: ${{ matrix.scheme }}
        platform: ${{ matrix.platform }}
        device: ${{ matrix.device }}
      run: |
        if [ $scheme = default ]; then scheme=$(cat default); fi
        xcodebuild build-for-testing -scheme $scheme -destination "platform=$platform,name=$device"
        
    - name: Test
      env:
        scheme: ${{ matrix.scheme }}
        platform: ${{ matrix.platform }}
        device: ${{ matrix.device }}
      run: |
        if [ $scheme = default ]; then scheme=$(cat default); fi
        xcodebuild test-without-building -scheme $scheme -destination "platform=$platform,name=$device"
